<?php

namespace ContainerMqht06L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CrlMJDgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CrlMJDg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CrlMJDg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Teacher' => ['privates', '.errored..service_locator.CrlMJDg.App\\Entity\\Teacher', NULL, 'Cannot autowire service ".service_locator.CrlMJDg": it references class "App\\Entity\\Teacher" but no such service exists.'],
        ], [
            'Teacher' => 'App\\Entity\\Teacher',
        ]);
    }
}
