<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2IqPuu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2IqPuu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC2IqPuu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC2IqPuu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC2IqPuu\App_KernelDevDebugContainer([
    'container.build_hash' => 'C2IqPuu',
    'container.build_id' => '89f42c03',
    'container.build_time' => 1607449986,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2IqPuu');
