<?php

namespace ContainerC2IqPuu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7Vnmxn3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7Vnmxn3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7Vnmxn3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Student' => ['privates', '.errored..service_locator.7Vnmxn3.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.7Vnmxn3": it references class "App\\Entity\\Student" but no such service exists.'],
        ], [
            'Student' => 'App\\Entity\\Student',
        ]);
    }
}
